[package]
name = "buddhabrot"
version = "0.1.0"
authors = ["Sid-003 <siddhartha4030@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
rand = "0.8.3"
rayon = "1.5"
